syntax = "proto3";

import "google/protobuf/timestamp.proto";

package event;

option go_package = "github.com/Estriper0/protobuf_eventhub/gen/event;event";

service Event {
    rpc GetAll(EmptyRequest) returns (GetAllResponse);
    rpc GetAllByCreator(GetAllByCreatorRequest) returns (GetAllResponse);
    rpc GetAllByStatus(GetAllByStatusRequest) returns (GetAllResponse);
    rpc GetById(GetByIdRequest) returns (GetByIdResponse);
    rpc Create(CreateRequest) returns (CreateResponse);
    rpc DeleteById(DeleteByIdRequest) returns (DeleteByIdResponse);
    rpc Update(UpdateRequest) returns (EmptyResponse);
    rpc Register(RegisterRequest) returns (EmptyResponse);
    rpc CancellRegister(CancellRegisterRequest) returns (EmptyResponse);
    rpc GetAllByUser(GetAllByUserRequest) returns (GetAllByUserResponse);
    rpc GetAllUsersByEvent(GetAllUsersByEventRequest) returns (GetAllUsersByEventResponse);
}

message EmptyRequest {}
message EmptyResponse {}

message EventElem {
    int64 id = 1;
    string title = 2;
    string about = 3;
    google.protobuf.Timestamp start_date = 4;
    string location = 5;
    string status = 6;
    int32 max_attendees = 7;
    int32 current_attendance = 8;
    string creator = 9;
}

message GetAllResponse {
    repeated EventElem events = 1;
}

message GetAllByCreatorRequest {
    string creator = 1;
}

message GetAllByStatusRequest {
    string status = 1;
}

message GetByIdRequest {
    int64 id = 1;
}

message GetByIdResponse {
    int64 id = 1;
    string title = 2;
    string about = 3;
    google.protobuf.Timestamp start_date = 4;
    string location = 5;
    string status = 6;
    int32 max_attendees = 7;
    int32 current_attendance = 8;
    string creator = 9;
}

message CreateRequest {
    string title = 2;
    string about = 3;
    google.protobuf.Timestamp start_date = 4;
    string location = 5;
    string status = 6;
    int32 max_attendees = 7;
    string creator = 8;
}

message CreateResponse {
    int64 id = 1;
}

message DeleteByIdRequest {
    int64 id = 1;
}

message DeleteByIdResponse {
    int64 id = 1;
}

message UpdateRequest {
    int64 id = 1;
    string title = 2;
    string about = 3;
    google.protobuf.Timestamp start_date = 4;
    string location = 5;
    string status = 6;
    int32 max_attendees = 7;
}

message RegisterRequest {
    string user_id = 1;
    int64 event_id = 2;
}

message CancellRegisterRequest {
    string user_id = 1;
    int64 event_id = 2;
}

message GetAllByUserRequest {
    string user_id = 1;
}

message GetAllByUserResponse {
    repeated EventElem events = 1;
}

message GetAllUsersByEventRequest {
    string event_id = 1;
}

message GetAllUsersByEventResponse {
    repeated string users_id = 1;
}
